<#
.SYNOPSIS
  Turns the in-game self-test log (.testprofile\Player.log) into docs\TEST_REPORT.md.
.DESCRIPTION
  Only the "[SELFTEST]" lines are copied (they contain no file paths or personal data), plus the game
  version and the package hash the run was checked against.
#>
[CmdletBinding()]
param([string]$Package)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$log = Join-Path $root ".testprofile\Player.log"
if (-not (Test-Path $log)) { throw "No test log found. Run Tools\Test-InGame.ps1 first." }
$lines = Get-Content $log
$test = $lines | Where-Object { $_ -match "\[SELFTEST\]" } | ForEach-Object { $_ -replace '^.*\[SELFTEST\]\s*', '' }
$result = $test | Where-Object { $_ -match "^SELFTEST RESULT" } | Select-Object -Last 1
$gameVersion = ($lines | Where-Object { $_ -match "^RimWorld \d" } | Select-Object -First 1)
$mods = (($lines | Where-Object { $_ -match "^\s+- " } | ForEach-Object { $_.Trim().TrimStart("-").Trim() } | Select-Object -Unique) -join ", ")
[xml]$about = Get-Content (Join-Path $root "Mod\About\About.xml") -Raw
$version = $about.ModMetaData.modVersion

$hash = ""
if ($Package) {
    $manifest = Get-ChildItem (Join-Path $root "Release") -Filter "*.sha256.txt" | Select-Object -First 1
    if ($manifest) { $hash = (Get-FileHash $manifest.FullName -Algorithm SHA256).Hash.ToLower() }
}

$out = New-Object System.Collections.Generic.List[string]
$out.Add("# In-game test report")
$out.Add("")
$out.Add("Generated by ``Tools/New-TestReport.ps1`` from the self-test log of the packaged mod.")
$out.Add("")
$out.Add("* Mod version: **$version**")
$out.Add("* Game: **$gameVersion**")
$out.Add("* Mods loaded in the test profile: $mods (Ideology is added automatically by the game's quick-test mode)")
if ($hash) { $out.Add("* Release manifest SHA-256: ``$hash``") }
$out.Add("* **$result**")
$out.Add("")
$out.Add("Every line is one check run inside the live game with real colonists and ticks. A check only")
$out.Add("passes when the game actually did the thing (colonists built the rack, serviced it, hauled the")
$out.Add("cartridges, a trader paid silver, the save reloaded with identical values, and so on).")
$out.Add("")
$out.Add("| Result | Check |")
$out.Add("| --- | --- |")
foreach ($l in $test) {
    if ($l -match "^(PASS|FAIL) (.*)$") {
        $text = $Matches[2].Replace("|", "/")
        $out.Add("| $($Matches[1]) | $text |")
    }
}
$out.Add("")
$out.Add("## Run information")
$out.Add("")
foreach ($l in $test) { if ($l -match "^info ") { $out.Add("* " + $l.Substring(5)) } }
$path = Join-Path $root "docs\TEST_REPORT.md"
$out | Set-Content -Encoding UTF8 $path
Write-Host "Wrote $path ($($test.Count) test lines)"

